"""Product-still generator — Gemini 2.5 Flash Image ("nano banana").

Why this exists: Imagen cannot be conditioned on an image (GenerateImagesConfig
has no reference/subject field), so a product still generated by Imagen shows an
INVENTED product. This model takes the reel's actual product photos as input and
generates a new still that keeps the real product's appearance.

Follows the CLI contract in src/lib/generators/base.py:
    python3 nanobanana_generator.py <prompt> <negative_prompt> <output> \
        [--base64] [--model <id>] [--ref <path> ...] [--persona <path>]

--ref is REQUIRED here: without reference photos this model has no advantage
over Imagen, and silently generating an unconditioned image is exactly the
failure this generator exists to prevent.

Two modes:
  * product still (default): --ref are product photos; the still reproduces the
    product faithfully in a new scene.
  * presenter composite (--persona <path>): the persona image is a real person
    (an avatar's still) and --ref are products; the output is that SAME person
    presenting the product, for HeyGen's type:'image' animate-a-photo render.
    This is how a product ends up IN the avatar shot (held), not behind it.
"""

import os
import sys

from google import genai
from google.genai import types

from generators.base import fail, load_env, parse_cli_args

# Only used when --model is absent; the id lives in DB config
# (clients.model_visual_product_image) per migration 0005.
DEFAULT_MODEL = "gemini-2.5-flash-image"

# 9:16 vertical is the product. Reels are 1080x1920; 2K keeps detail after the
# assembly scale/crop pass.
ASPECT_RATIO = "9:16"
IMAGE_SIZE = "2K"


def build_prompt(prompt, negative_prompt):
    """The reference photos are the source of truth for the product's look."""
    text = (
        "Generate a single vertical 9:16 photographic image for a product reel.\n\n"
        "The attached reference photo(s) show the EXACT product this image must feature. "
        "Reproduce that product faithfully — same shape, colour, materials, proportions, "
        "labelling and branding. Do not redesign it, do not alter its text or logos, and "
        "do not substitute a similar-looking product.\n\n"
        f"SHOT TO CREATE:\n{prompt}"
    )
    if negative_prompt and negative_prompt.strip():
        text += f"\n\nAVOID: {negative_prompt.strip()}"
    return text


def build_composite_prompt(prompt, negative_prompt):
    """Preserve the PERSON (image 1) and place the PRODUCT (image 2+) in-frame.

    The output feeds HeyGen's type:'image' animate-a-photo render, so identity
    fidelity matters as much as product fidelity: the animated face must still
    read as the same presenter.
    """
    text = (
        "Image 1 shows a real person (a video presenter). The remaining image(s) show a product.\n\n"
        "Create a single photorealistic vertical 9:16 image of the EXACT SAME person from image 1 — "
        "identical face, glasses, facial hair, skin tone, hair and clothing — now naturally holding and "
        "presenting the product at chest height in one hand, facing the camera. Keep the product's exact "
        "colours, shape, proportions and labelling. Do NOT change the person's identity, and do NOT "
        "redesign the product. Keep the framing head-and-shoulders so the face is clear for animation.\n\n"
        f"DIRECTION:\n{prompt}"
    )
    if negative_prompt and negative_prompt.strip():
        text += f"\n\nAVOID: {negative_prompt.strip()}"
    return text


def load_reference_parts(paths, output_filename):
    """Read each reference photo as an inline image part.

    A missing file is fatal: generating without the references would produce a
    fictional product, which is worse than a failed stage because nothing
    downstream can detect it.
    """
    parts = []
    for p in paths:
        if not os.path.exists(p):
            fail(output_filename, f"reference image not found: {p}", retryable=False)
        ext = os.path.splitext(p)[1].lower()
        mime = "image/png" if ext == ".png" else "image/webp" if ext == ".webp" else "image/jpeg"
        with open(p, "rb") as f:
            parts.append(types.Part.from_bytes(data=f.read(), mime_type=mime))
    return parts


def extract_image_bytes(response):
    """Pull the generated image out of the response, or return None.

    The model can answer with text (e.g. a safety refusal) instead of an image,
    so this must not assume a part is an image.
    """
    for candidate in response.candidates or []:
        content = getattr(candidate, "content", None)
        for part in getattr(content, "parts", None) or []:
            inline = getattr(part, "inline_data", None)
            if inline and inline.data:
                return inline.data
    return None


def response_text(response):
    """Any text the model returned — usually the reason it declined."""
    chunks = []
    for candidate in response.candidates or []:
        content = getattr(candidate, "content", None)
        for part in getattr(content, "parts", None) or []:
            if getattr(part, "text", None):
                chunks.append(part.text)
    return " ".join(chunks).strip()


def parse_persona():
    """Read an optional --persona <path> from argv (composite mode).

    parse_cli_args() ignores unknown flags, so --persona and its value pass
    through it untouched; this reads them separately to avoid changing the shared
    CLI contract that veo/imagen also depend on.
    """
    argv = sys.argv[1:]
    for i, tok in enumerate(argv):
        if tok == "--persona" and i + 1 < len(argv):
            return argv[i + 1]
    return None


def generate(prompt, negative_prompt, output_filename, model=None, reference_paths=None, persona_path=None):
    env = load_env()
    api_key = env.get("GEMINI_API_KEY") or env.get("VEO_API_KEY")
    if not api_key:
        fail(output_filename, "GEMINI_API_KEY or VEO_API_KEY is not set.", retryable=False)

    reference_paths = reference_paths or []
    if not reference_paths:
        fail(
            output_filename,
            "nanobanana_generator requires at least one --ref product photo. "
            "Unconditioned stills belong in imagen_generator.py.",
            retryable=False,
        )

    composite = persona_path is not None
    if composite and not os.path.exists(persona_path):
        fail(output_filename, f"persona image not found: {persona_path}", retryable=False)

    model = model or DEFAULT_MODEL
    print(f"[{output_filename}] Model: {model}")

    client = genai.Client(api_key=api_key)

    if composite:
        print(f"[{output_filename}] Compositing 1 persona + {len(reference_paths)} product image(s).")
        # Persona FIRST so "image 1" in the prompt is the person.
        contents = load_reference_parts([persona_path], output_filename)
        contents += load_reference_parts(reference_paths, output_filename)
        contents.append(types.Part.from_text(text=build_composite_prompt(prompt, negative_prompt)))
    else:
        print(f"[{output_filename}] Conditioning on {len(reference_paths)} product reference image(s).")
        contents = load_reference_parts(reference_paths, output_filename)
        contents.append(types.Part.from_text(text=build_prompt(prompt, negative_prompt)))

    print(f"[{output_filename}] Generating {'presenter composite' if composite else 'product still'}...")
    response = client.models.generate_content(
        model=model,
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            image_config=types.ImageConfig(aspect_ratio=ASPECT_RATIO, image_size=IMAGE_SIZE),
        ),
    )

    image_bytes = extract_image_bytes(response)
    if not image_bytes:
        detail = response_text(response) or "no image and no explanation returned"
        # Retryable, for the same reason as Veo's filtered case: a "safety"
        # non-answer from these models is not reliably deterministic, and a
        # rejected generation is not billed. Contract/config errors above are the
        # permanent ones; a content refusal gets its retries.
        fail(output_filename, f"model returned no image — {detail[:400]}")

    with open(output_filename, "wb") as f:
        f.write(image_bytes)
    print(f"[{output_filename}] {'Composite' if composite else 'Product still'} saved successfully as: {output_filename}")


if __name__ == "__main__":
    prompt, negative_prompt, output_filename, model, reference_images = parse_cli_args()
    generate(prompt, negative_prompt, output_filename, model, reference_images, parse_persona())
